version: '3.2'

services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - tasks-network
    depends_on:
      - keycloak

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=debug
      - DB_VENDOR=h2
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    ports:
      - "8180:8080"
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    networks:
      - tasks-network

  go-backend:
    container_name: go-backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - tasks-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak

networks:
  tasks-network: